# Generated by Django 5.1.2 on 2024-10-15 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Settings',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='setting',
            new_name='settings',
        ),
    ]
