# Generated by Django 5.1.2 on 2024-10-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_message_options_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Settings'},
        ),
    ]
